### ISSUE TITLE
Implement NetPyNE bits to run Hay model

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/L5bPyrCellHayEtAl2011#8]
Bits in NetPyNE: https://github.com/suny-downstate-medical-center/netpyne/blob/e10aa9187afca9be5d54c11c7ca21abaa8382de7/netpyne/conversion/neuromlFormat.py#L1299

Other examples to test with:

https://github.com/OpenSourceBrain/ghk-nernst

**Comment by sanjayankur31** [comment]
Currently running into trouble with fraction along:

```
pyNeuroML >>> DEBUG - Processing segment: <Segment|4067|Seg0_axon_0>
pyNeuroML >>> CRITICAL - Segment (<Segment|4067|Seg0_axon_0>) must be attached to parent (<parent segment="9" fractionAlong="0.9999544"/>
) at proximal or distal point
Traceback (most recent call last):
  File "/home/asinha/Documents/02_Code/00_mine/models/L5bPyrCellHayEtAl2011/neuroConstruct/generatedNeuroML2/LEMS_TestL5PC_netpyne.py", line 269, in <module>
    ns.run()
  File "/home/asinha/Documents/02_Code/00_mine/models/L5bPyrCellHayEtAl2011/neuroConstruct/generatedNeuroML2/LEMS_TestL5PC_netpyne.py", line 155, in run
    self.gids = sim.importNeuroML2SimulateAnalyze(self.nml2_file_name,self.simConfig)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asinha/Documents/02_Code/00_mine/NeuroML/software/netpyne/netpyne/sim/wrappers.py", line 635, in importNeuroML2SimulateAnalyze
    return sim.importNeuroML2(fileName, simConfig, simulate=True, analyze=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asinha/Documents/02_Code/00_mine/NeuroML/software/netpyne/netpyne/conversion/neuromlFormat.py", line 1751, in importNeuroML2
    currParser.parse(fileName)
  File "/home/asinha/.local/share/virtualenvs/neuroml-311-dev/lib/python3.11/site-packages/neuroml/hdf5/NeuroMLXMLParser.py", line 124, in parse
    self.netHandler.handle_population(
  File "/home/asinha/Documents/02_Code/00_mine/NeuroML/software/netpyne/netpyne/conversion/neuromlFormat.py", line 1208, in handle_population
    assert fract == 1.0 or fract == 0.0
                           ^^^^^^^^^^^^
AssertionError

```

Question: why is it compulsory that the segment only be attached to the parent segment at either 0, or 1 (prox or distal) points?
